routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web']], function () {

    Auth::routes();
    /*--------------------------ADMIN--------------------------------------*/
    Route::prefix('admin')->middleware('auth')->group(function () {

        Route::get('/', function () {
            return view('backend.pages.dashboard');
        });

        Route::resource('rekening','Admin\RekeningController');
        Route::post('rekening/get', 'Admin\RekeningController@getAllRekening')->name('rekening.get');
        Route::patch('rekening/{rekening}', 'Admin\RekeningController@store')->name('rekening.update');
        Route::post('rekening/getList', 'Admin\RekeningController@getRekeningList')->name('rekening.getList');

        Route::resource('jenis','Admin\JenisController');
        Route::post('jenis/get', 'Admin\JenisController@getAllJenis')->name('jenis.get');
        Route::patch('jenis/{jeni}', 'Admin\JenisController@store')->name('jenis.update');
        Route::post('jenis/getList', 'Admin\JenisController@getJenisList')->name('jenis.getList');

        Route::resource('pengkhususan','Admin\PengkhususanController');
        Route::post('pengkhususan/get', 'Admin\PengkhususanController@getAllKhusus')->name('pengkhususan.get');
        Route::patch('pengkhususan/{pengkhususan}', 'Admin\PengkhususanController@store')->name('pengkhususan.update');
        Route::post('pengkhususan/getList', 'Admin\PengkhususanController@getPengkhususanList')->name('pengkhususan.getList');

        Route::resource('donasi','Admin\DonasiController');
        Route::post('donasi/get', 'Admin\DonasiController@getAllDonasi')->name('donasi.get');
        Route::post('donasi/ganti-status', 'Admin\DonasiController@gantiStatus');
        Route::post('donasi/download-bukti', 'Admin\DonasiController@downloadBukti');

        Route::resource('donatur','Admin\DonaturController');
        Route::post('donatur/get', 'Admin\DonaturController@getAllDonatur')->name('donatur.get');
        Route::post('donatur/getList', 'Admin\DonaturController@getDonaturList')->name('donatur.getList');

    });
    /*--------------------------FRONTEND--------------------------------------*/

    Route::get('/', function (){
        return view('welcome');
    });
    Route::get('donasi', 'Front\HomeController@index');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::post('home-donatur/getList', 'Front\DonaturController@getDonaturList');
    Route::get('home-donatur/{id}', 'Front\DonaturController@getDonatur');
    Route::post('home-pengkhususan/getList', 'Front\HomeController@getPengkhususanList')->name('home-pengkhususan.getList');


});

app/Pengkhususan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengkhususan extends Model
{

    //is_deleted 1 = di delete
    protected $table = "pengkhususan";

    protected $fillable = [
        'jenis_id','pengkhususan', 'keterangan', 'is_deleted'
    ];

    public function jenis(){
        return $this->belongsTo('App\Jenis','jenis_id','id');
    }

}

app/Http/Controllers/Admin/PengkhususanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jenis;
use App\Pengkhususan;
use App\Rekening;
use Illuminate\Http\Request;

class PengkhususanController extends Controller
{

    public function index()
    {
        return view('backend.pages.master.pengkhususan.index');
    }

    public function getAllKhusus(Request $request){

        if (!$request->ajax()) return response('Forbidden', 403);

        $input = $request->all();

        // DataTable Default
        $length = (int)@$input['length'] ?? 10;
        $start = (int)@$input['start'];
        $search = @$input['search'];
        $order = @$input['order'];
        $status = @$input['status'];

        $data = Pengkhususan::with('jenis')->where('is_deleted',0);

        $count = $data->count();
        $table = [];
        $table['recordsFiltered'] = $count;
        $table['recordsTotal'] = $count;

        // Search
        if (!empty($search) AND !empty($search['value'])) {
            $data = $data->where(function ($query) use ($search) {
                $query->orWhere('id', 'like', '%' . $search['value'] . '%');
                $query->orWhere('pengkhususan', 'like', '%' . $search['value'] . '%');
            });

            $table['recordsFiltered'] = $data->count(); // Menghitung jumlah data yang ditemukan berdasarkan search. Di datatables nya nanti muncul Total xx From xx (Filtered from xxxx)
        }

        $data_tmp = $data->skip($start)->take($length);

        // Init
        $i = $start + 1;
        foreach ($data_tmp->get() as $row) {
            $d = [];

            $d[] = $i++;

            $d[] = $row->jenis->jenis;
            $d[] = $row->pengkhususan;
            $btn = '<a href="' . route('pengkhususan.edit', $row->id) . '" class="btn  btn-primary" style="margin-right: 3px;">  <i class="far fa-edit"></i></a>';
            $btn .= '<a href="#" data-id="' . $row->id . '" class="btn btn-danger btn-del " >  <i class="fas fa-trash-alt"></i></a>';

            $d[] = sprintf('<span style="overflow: visible; position: relative; width: 110px;">%s</span>', $btn);
            $d["DT_RowId"] = ($i - 1) . '#' . $row['_id'];
            $table['data'][] = $d;
        }

        if (empty($table['data'])) {
            $table['recordsTotal'] = $count;
            $table['recordsFiltered'] = 0;
            $table['aaData'] = [];
        }

        return response()->json($table);
    }


    public function create()
    {
        $data['jenis'] = Jenis::all();
        return view('backend.pages.master.pengkhususan.form',$data);
    }

    public function store(Request $request, $id = 0)
    {
//        dd($request->all());
        $rules = [
            'jenis_id' => 'required',
            'pengkhususan' => 'required'
        ];
        $customMessages = [
            'jenis_id.required' => 'Field Jenis Donasi Wajib Diisi!',
            'pengkhususan.required' => 'Field Pengkhususan Donasi Wajib Diisi!'
        ];
        $this->validate($request, $rules, $customMessages);

        $input = $request->all();
        if ($request->method() == "PATCH") {
            $jenis = Pengkhususan::find($id);
            $status = $jenis->update($input);
        } else {
            $status = Pengkhususan::create($input);
        }
        if ($status) {
            return redirect()->route('pengkhususan.index')->with('success', 'Data berhasil ' . (empty($id) ? 'ditambah' : 'diubah'));
        }

    }



    public function edit($id)
    {
        $data['khusus'] = Pengkhususan::find($id);
        $data['jenis'] = Jenis::all();
        return view('backend.pages.master.pengkhususan.form',$data);
    }


    public function destroy($id)
    {
        $jenis = Pengkhususan::find($id);
        $jenis->is_deleted = 1;
        $status = $jenis->save();

        if ($status) {
            return 1;
        } else {
            return 0;
        }
    }
    public function getPengkhususanList(Request $request)
    {
//        dd($request->all());
        $input = $request->all();

        $data = Pengkhususan::where('is_deleted', 0)->orderBy('id');
        if (@$input['search']) $data = $data->where('pengkhususan', 'like', '%' . $input['search'] . '%');

        $count = $data->count();

        if ($count > 10) $more = TRUE;
        else $more = FALSE;

        $data = $data->take(10)->skip(10 * ($input['page']-1))->get();
        $return = [];
        foreach ($data as $row) {
            $return[] = [
                'id' => $row->id,
                'text' => $row->jenis->jenis.' - '.$row->pengkhususan,
            ];
        }

        return ['results' => $return, 'pagination' => ['more' => $more]];
    }
}

resources/views/backend/pages/master/pengkhususan/form.blade.php
@extends('backend.layouts.app')
@section('title','Dash')
@section('pengkhususan','active')

@push('styles')
    <style>

    </style>
@endpush
@section('content')

    <div class="main-content">
        <sectiion>
            <div class="section-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item "><a href="{{route('jenis.index')}}">Data Pengkhususan Donasi</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{@$khusus ? "Ubah" : "Tambah"}} Data Pengkhususan Donasi</li>
                    </ol>
                </nav>
            </div>
        </sectiion>
        <section class="section">
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{@$khusus ? "Ubah" : "Tambah"}} Data Pengkhususan Donasi</h4>
                            </div>

                            <div class="card-body">
                                <form action="{{@$khusus ? route('pengkhususan.update', $khusus->id) : route('pengkhususan.store')}}"  method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if(@$khusus)
                                        {{method_field('patch')}}
                                    @endif
                                    <div class="form-group">
                                        <label for="jenis_id">Jenis Donasi</label>
                                        <select name="jenis_id" id="jenis_id" class="form-control">
                                            @foreach($jenis as $row)
                                            <option value="{{$row->id}}" {{@$khusus->jenis_id == $row->id ? 'selected' : ''}}> {{$row->jenis}} </option>
                                            @endforeach
                                        </select>

                                    </div>
                                    <div class="form-group">
                                        <label for="pengkhususan">Pengkhususan Donasi</label>
                                        <input id="pengkhususan" name="pengkhususan" type="text" class="form-control"
                                               value="{{old('pengkhususan',@$khusus->pengkhususan)}}">
                                    </div>

                                    <div class="form-button text-right">
                                        <a href="{{route('jenis.index')}}" class="btn btn-warning">Kembali</a>
                                        <button class="btn btn-primary" type="submit">Simpan</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {

        });

    </script>

@endpush

resources/views/backend/pages/master/pengkhususan/index.blade.php
@extends('backend.layouts.app')
@section('title','Dash')
@section('pengkhususan','active')

@push('styles')
    <style>

    </style>
@endpush
@section('content')

    <div class="main-content">
        <sectiion>
            <div class="section-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Data Pengkhususan Donasi</li>

                        <li class="breadcrumb-item"><a href="#"></a></li>
                        {{--                        <li class="breadcrumb-item active"><a href="#">Data Jenis</a></li>--}}
{{--                        <li class="breadcrumb-item active" aria-current="page">Data</li>--}}
                    </ol>
                </nav>
            </div>
        </sectiion>
        <section class="section">
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Master Data Pengkhususan Donasi</h4>
                                <div class="card-header-action">
                                    <a href="{{ route('pengkhususan.create') }}" class="btn btn-sm btn-primary float-right"><i class="fas fa-plus"></i> Tambah</a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-pengkhususan">
                                        <thead>
                                        <tr>
                                            <th class="text-center">
                                                #
                                            </th>
                                            <th>Jenis Donasi</th>
                                            <th>Pengkhususan</th>
                                            <th>Aksi</th>
                                        </tr>
                                        </thead>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $('#table-pengkhususan').DataTable( {
                deferRender: true,
                serverSide: true,
                processing: true,
                stateSave: true,
                scrollX: false,
                ajax: {
                    url: '{!! route('pengkhususan.get') !!}',
                    type: 'POST',
                    data: function (e) {
                        e._token = '{{ csrf_token() }}';
                        return e;
                    }
                }
            });

            $(document).on('click','.btn-del', function () {
                var id = $(this).data('id');
                swal({
                    title: 'Apakah Anda Yakin?',
                    text: 'Data yang telah dihapus tidak bisa dikembalikan!',
                    icon: 'warning',
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            $.ajax({
                                type: "delete",
                                url: "{{ url('admin/pengkhususan') }}/"+id,
                                data: {
                                    '_token' : '{{ csrf_token() }}'
                                },
                                success: function (response) {
                                    if(response == 1){
                                        swal('Data berhasil dihapus!', {
                                            icon: 'success',
                                        });
                                        setTimeout(() => {
                                            location.reload();
                                        }, 2000);
                                    }else{
                                        swal('Data gagal dihapus!', {
                                            icon: 'error',
                                        });
                                    }
                                }
                            });

                        } else {

                        }
                    });
            });
        });

    </script>

@endpush