routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web']], function () {

    Auth::routes();
    /*--------------------------ADMIN--------------------------------------*/
    Route::prefix('admin')->middleware('auth')->group(function () {

        Route::get('/', function () {
            return view('backend.pages.dashboard');
        });

        Route::resource('rekening','Admin\RekeningController');
        Route::post('rekening/get', 'Admin\RekeningController@getAllRekening')->name('rekening.get');
        Route::patch('rekening/{rekening}', 'Admin\RekeningController@store')->name('rekening.update');
        Route::post('rekening/getList', 'Admin\RekeningController@getRekeningList')->name('rekening.getList');

        Route::resource('jenis','Admin\JenisController');
        Route::post('jenis/get', 'Admin\JenisController@getAllJenis')->name('jenis.get');
        Route::patch('jenis/{jeni}', 'Admin\JenisController@store')->name('jenis.update');
        Route::post('jenis/getList', 'Admin\JenisController@getJenisList')->name('jenis.getList');

        Route::resource('pengkhususan','Admin\PengkhususanController');
        Route::post('pengkhususan/get', 'Admin\PengkhususanController@getAllKhusus')->name('pengkhususan.get');
        Route::patch('pengkhususan/{pengkhususan}', 'Admin\PengkhususanController@store')->name('pengkhususan.update');
        Route::post('pengkhususan/getList', 'Admin\PengkhususanController@getPengkhususanList')->name('pengkhususan.getList');

        Route::resource('donasi','Admin\DonasiController');
        Route::post('donasi/get', 'Admin\DonasiController@getAllDonasi')->name('donasi.get');
        Route::post('donasi/ganti-status', 'Admin\DonasiController@gantiStatus');
        Route::post('donasi/download-bukti', 'Admin\DonasiController@downloadBukti');

        Route::resource('donatur','Admin\DonaturController');
        Route::post('donatur/get', 'Admin\DonaturController@getAllDonatur')->name('donatur.get');
        Route::post('donatur/getList', 'Admin\DonaturController@getDonaturList')->name('donatur.getList');

    });
    /*--------------------------FRONTEND--------------------------------------*/

    Route::get('/', function (){
        return view('welcome');
    });
    Route::get('donasi', 'Front\HomeController@index');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::post('home-donatur/getList', 'Front\DonaturController@getDonaturList');
    Route::get('home-donatur/{id}', 'Front\DonaturController@getDonatur');
    Route::post('home-pengkhususan/getList', 'Front\HomeController@getPengkhususanList')->name('home-pengkhususan.getList');


});

app/Jenis.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jenis extends Model
{

    //is_deleted 1 = di delete
    protected $table = "jenis";

    protected $fillable = [
        'jenis', 'keterangan', 'is_deleted'
    ];

    public function pengkhususan(){
        return $this->hasMany('App\Pengkhususan','jenis_id','id');
    }
}

app/Http/Controllers/Admin/JenisController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jenis;
use App\Pengkhususan;
use Illuminate\Http\Request;

class JenisController extends Controller
{

    public function index()
    {
        return view('backend.pages.master.jenis.index');
    }

    public function getAllJenis(Request $request){

        if (!$request->ajax()) return response('Forbidden', 403);

        $input = $request->all();

        // DataTable Default
        $length = (int)@$input['length'] ?? 10;
        $start = (int)@$input['start'];
        $search = @$input['search'];
        $order = @$input['order'];
        $status = @$input['status'];

        $data = Jenis::where('is_deleted',0)->with('pengkhususan');

        $count = $data->count();
        $table = [];
        $table['recordsFiltered'] = $count;
        $table['recordsTotal'] = $count;

        // Search
        if (!empty($search) AND !empty($search['value'])) {
            $data = $data->where(function ($query) use ($search) {
                $query->orWhere('id', 'like', '%' . $search['value'] . '%');
                $query->orWhere('nama_bank', 'like', '%' . $search['value'] . '%');
            });

            $table['recordsFiltered'] = $data->count(); // Menghitung jumlah data yang ditemukan berdasarkan search. Di datatables nya nanti muncul Total xx From xx (Filtered from xxxx)
        }

        $data_tmp = $data->skip($start)->take($length);

        // Init
        $i = $start + 1;
        foreach ($data_tmp->get() as $row) {
            $d = [];

            $d[] = $i++;

            $d[] = $row->jenis;
            $d[] = $row->keterangan;

            $jenis = '';
            foreach($row->pengkhususan as $key=>$val){
                if ($val->is_deleted == 0){
                    $jenis .= '- '.$val->pengkhususan . '<br>';
                }
            }

            $d[] = $jenis;
            $btn = '<a href="' . route('jenis.edit', $row->id) . '" class="btn  btn-primary" style="margin-right: 3px;">  <i class="far fa-edit"></i></a>';
            $btn .= '<a href="#" data-id="' . $row->id . '" class="btn btn-danger btn-del " >  <i class="fas fa-trash-alt"></i></a>';

            $d[] = sprintf('<span style="overflow: visible; position: relative; width: 110px;">%s</span>', $btn);
            $d["DT_RowId"] = ($i - 1) . '#' . $row['_id'];
            $table['data'][] = $d;
        }

        if (empty($table['data'])) {
            $table['recordsTotal'] = $count;
            $table['recordsFiltered'] = 0;
            $table['aaData'] = [];
        }

        return response()->json($table);
    }


    public function create()
    {
        return view('backend.pages.master.jenis.form');
    }

    public function store(Request $request, $id = 0)
    {
//        dd($request->all());
        $rules = [
            'jenis' => 'required'
        ];
        $customMessages = [
            'jenis.required' => 'Field Jenis Donasi Wajib Diisi!'
        ];
        $this->validate($request, $rules, $customMessages);

        $input = $request->all();

        $jenis = Jenis::updateOrCreate(['id' => $id], $input);

        $detail = Pengkhususan::where('jenis_id', $jenis->id)->get();

        if ($detail){
            foreach($detail as $row){
                $row->is_deleted = 1;
                $row->save();
            }
        }

        for ($i = 1; $i <= count($input['khusus']); $i++) {
            $st = [
                'jenis_id' => $jenis->id,
                'pengkhususan' =>$input['khusus'][$i - 1]['pengkhususan']
            ];
            $pengkhususan = Pengkhususan::create($st);
        }

        if ($pengkhususan) {
            return redirect()->route('jenis.index')->with('success', 'Data berhasil ' . (empty($id) ? 'ditambah' : 'diubah'));
        }

    }



    public function edit($id)
    {
        $jenis = Jenis::where('id', $id)->with('pengkhususan')->first();
        foreach ($jenis->pengkhususan as $row) {
            if ($row->is_deleted == 0){
                $d[] = [
                    'pengkhususan' => $row->pengkhususan,
                ];
            }
        }
        $data['pengkhususan'] = $d;
        $data['jenis'] = $jenis;

        return view('backend.pages.master.jenis.form',$data);
    }


    public function destroy($id)
    {
        $jenis = Jenis::find($id);
        $jenis->is_deleted = 1;
        $status = $jenis->save();

        if ($status) {
            return 1;
        } else {
            return 0;
        }
    }

    public function getJenisList(Request $request)
    {
        $input = $request->all();

        $data = Jenis::orderBy('id');
        if (@$input['search']) $data = $data->where('jenis', 'like', '%' . $input['search'] . '%');

        $count = $data->count();

        if ($count > 10) $more = TRUE;
        else $more = FALSE;

        $data = $data->take(10)->skip(10 * ($input['page'] - 1))->get();
        $return = [];
        foreach ($data as $row) {
            $return[] = [
                'id' => $row->id,
                'text' => $row->jenis,
            ];
        }

        return ['results' => $return, 'pagination' => ['more' => $more]];
    }
}

resources/views/backend/pages/master/jenis/form.blade.php
@extends('backend.layouts.app')
@section('title','Dash')
@section('jenis','active')

@push('styles')
    <style>

    </style>
@endpush
@section('content')

    <div class="main-content">
        <sectiion>
            <div class="section-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item "><a href="{{route('jenis.index')}}">Data Jenis Donasi</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{@$jenis ? "Ubah" : "Tambah"}} Data Jenis Donasi</li>
                    </ol>
                </nav>
            </div>
        </sectiion>
        <section class="section">
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{@$jenis ? "Ubah" : "Tambah"}} Data Jenis Donasi</h4>
                            </div>

                            <div class="card-body">
                                <form action="{{@$jenis ? route('jenis.update', $jenis->id) : route('jenis.store')}}"  method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if(@$jenis)
                                        {{method_field('patch')}}
                                    @endif
                                    <div class="form-group">
                                        <label for="jenis">Jenis Donasi</label>
                                        <input id="jenis" name="jenis" type="text" class="form-control"
                                           value="{{old('nama_bank',@$jenis->jenis)}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="keterangan">Keterangan</label>
                                        <textarea class="form-control" name="keterangan" id="keterangan" cols="30" rows="10">{{old('kode_bank',@$jenis->keterangan)}}</textarea>
                                    </div>

                                    <hr>
                                    <h6 style="font-size: 16px">Pengkhususan Jenis Donasi</h6>
                                    <div class="pk-repeater repeater">
                                        <div class="form-group">
                                            <div class="text-left">
                                                <button type="button" class="btn btn-sm btn-primary" data-repeater-create type="button">
                                                    <i class="fa fa-plus"></i> Tambah Pengkhususan
                                                </button>
                                            </div>
                                        </div>

                                        <div data-repeater-list="khusus">
                                            <div data-repeater-item>
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <label class="control-label label-kd3" for="subtema">Pengkhususan Zakat</label>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-sm-5">
                                                            <input type="text" name="pengkhususan" class="form-control"  placeholder="Masukan Jenis Pengkhususan" value="Default"/>
                                                        </div>

                                                        <div class="col-sm-1">
                                                            <button type="button" class="btn btn-danger btn-sm" data-repeater-delete><i class="fa fa-trash"></i></button>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-button text-right">
                                        <a href="{{route('jenis.index')}}" class="btn btn-warning">Kembali</a>
                                        <button class="btn btn-primary" type="submit">Simpan</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </div>

@endsection
@push('scripts')
    <script src="{{asset('assets/backend/')}}/js/jquery.repeater.min.js"></script>

    <script>
        $(document).ready(function () {
            $repeater = $('.repeater').repeater({
                show: function () {
                    $(this).slideDown();
                },
                hide: function (el) {
                    $(this).slideUp(el);
                }
            });

            @if(!empty($jenis))

            $repeater.setList({!! json_encode($pengkhususan) !!})
            @endif

        });
    </script>

@endpush

resources/views/backend/pages/master/jenis/index.blade.php
@extends('backend.layouts.app')
@section('title','Dash')
@section('jenis','active')

@push('styles')
    <style>

    </style>
@endpush
@section('content')

    <div class="main-content">
        <sectiion>
            <div class="section-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Data Jenis Donasi</li>

                        <li class="breadcrumb-item"><a href="#"></a></li>
                        {{--                        <li class="breadcrumb-item active"><a href="#">Data Jenis</a></li>--}}
{{--                        <li class="breadcrumb-item active" aria-current="page">Data</li>--}}
                    </ol>
                </nav>
            </div>
        </sectiion>
        <section class="section">
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Master Data Jenis Donasi</h4>
                                <div class="card-header-action">
                                    <a href="{{ route('jenis.create') }}" class="btn btn-sm btn-primary float-right"><i class="fas fa-plus"></i> Tambah</a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-jenis">
                                        <thead>
                                        <tr>
                                            <th class="text-center">
                                                #
                                            </th>
                                            <th>Jenis Donasi</th>
                                            <th>Keterangan</th>
                                            <th>Pengkhususan</th>
                                            <th>Aksi</th>
                                        </tr>
                                        </thead>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $('#table-jenis').DataTable( {
                deferRender: true,
                serverSide: true,
                processing: true,
                stateSave: true,
                scrollX: false,
                ajax: {
                    url: '{!! route('jenis.get') !!}',
                    type: 'POST',
                    data: function (e) {
                        e._token = '{{ csrf_token() }}';
                        return e;
                    }
                }
            });

            $(document).on('click','.btn-del', function () {
                var id = $(this).data('id');
                swal({
                    title: 'Apakah Anda Yakin?',
                    text: 'Data yang telah dihapus tidak bisa dikembalikan!',
                    icon: 'warning',
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            $.ajax({
                                type: "delete",
                                url: "{{ url('admin/jenis') }}/"+id,
                                data: {
                                    '_token' : '{{ csrf_token() }}'
                                },
                                success: function (response) {
                                    if(response == 1){
                                        swal('Data berhasil dihapus!', {
                                            icon: 'success',
                                        });
                                        setTimeout(() => {
                                            location.reload();
                                        }, 2000);
                                    }else{
                                        swal('Data gagal dihapus!', {
                                            icon: 'error',
                                        });
                                    }
                                }
                            });

                        } else {

                        }
                    });
            });
        });

    </script>

@endpush