routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['middleware' => ['web']], function () {

    Auth::routes();
    /*--------------------------ADMIN--------------------------------------*/
    Route::prefix('admin')->middleware('auth')->group(function () {

        Route::get('/', function () {
            return view('backend.pages.dashboard');
        });

        Route::resource('rekening','Admin\RekeningController');
        Route::post('rekening/get', 'Admin\RekeningController@getAllRekening')->name('rekening.get');
        Route::patch('rekening/{rekening}', 'Admin\RekeningController@store')->name('rekening.update');
        Route::post('rekening/getList', 'Admin\RekeningController@getRekeningList')->name('rekening.getList');

        Route::resource('jenis','Admin\JenisController');
        Route::post('jenis/get', 'Admin\JenisController@getAllJenis')->name('jenis.get');
        Route::patch('jenis/{jeni}', 'Admin\JenisController@store')->name('jenis.update');
        Route::post('jenis/getList', 'Admin\JenisController@getJenisList')->name('jenis.getList');

        Route::resource('pengkhususan','Admin\PengkhususanController');
        Route::post('pengkhususan/get', 'Admin\PengkhususanController@getAllKhusus')->name('pengkhususan.get');
        Route::patch('pengkhususan/{pengkhususan}', 'Admin\PengkhususanController@store')->name('pengkhususan.update');
        Route::post('pengkhususan/getList', 'Admin\PengkhususanController@getPengkhususanList')->name('pengkhususan.getList');

        Route::resource('donasi','Admin\DonasiController');
        Route::post('donasi/get', 'Admin\DonasiController@getAllDonasi')->name('donasi.get');
        Route::post('donasi/ganti-status', 'Admin\DonasiController@gantiStatus');
        Route::post('donasi/download-bukti', 'Admin\DonasiController@downloadBukti');

        Route::resource('donatur','Admin\DonaturController');
        Route::post('donatur/get', 'Admin\DonaturController@getAllDonatur')->name('donatur.get');
        Route::post('donatur/getList', 'Admin\DonaturController@getDonaturList')->name('donatur.getList');

    });
    /*--------------------------FRONTEND--------------------------------------*/

    Route::get('/', function (){
        return view('welcome');
    });
    Route::get('donasi', 'Front\HomeController@index');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::resource('fdonatur', 'Front\DonaturController');
    Route::post('home-donatur/getList', 'Front\DonaturController@getDonaturList');
    Route::get('home-donatur/{id}', 'Front\DonaturController@getDonatur');
    Route::post('home-pengkhususan/getList', 'Front\HomeController@getPengkhususanList')->name('home-pengkhususan.getList');


});

app/Donatur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Donatur extends Model
{
    protected $table = "donatur";

    protected $fillable = [
        'sapaan', 'nama', 'email','alamat',
        'telepon','is_deleted'
    ];

    public function donasi(){
        return $this->hasMany('App\Donasi', 'donatur_id','id');
    }
}

app/Http/Controllers/Admin/DonaturController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Donasi;
use App\Donatur;
use App\Http\Controllers\Controller;
use App\Jenis;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class DonaturController extends Controller
{

    public function index()
    {
        return view('backend.pages.donatur.index');
    }

    public function getAllDonatur(Request $request){

        if (!$request->ajax()) return response('Forbidden', 403);

        $input = $request->all();

        // DataTable Default
        $length = (int)@$input['length'] ?? 10;
        $start = (int)@$input['start'];
        $search = @$input['search'];
        $order = @$input['order'];
        $status = @$input['status'];

        $data = Donatur::where('is_deleted',0)->orderBy('id', 'ASC');

        $count = $data->count();
        $table = [];
        $table['recordsFiltered'] = $count;
        $table['recordsTotal'] = $count;

        // Search
        if (!empty($search) AND !empty($search['value'])) {
            $data = $data->where(function ($query) use ($search) {
                $query->orWhere('id', 'like', '%' . $search['value'] . '%');
                $query->orWhere('kode_verifikasi', 'like', '%' . $search['value'] . '%');
                $query->orWhere('nama', 'like', '%' . $search['value'] . '%');
            });

            $table['recordsFiltered'] = $data->count(); // Menghitung jumlah data yang ditemukan berdasarkan search. Di datatables nya nanti muncul Total xx From xx (Filtered from xxxx)
        }

        $data_tmp = $data->skip($start)->take($length);

        // Init
        $i = $start + 1;
        foreach ($data_tmp->get() as $row) {
            $d = [];

            $d[] = $i++;

            $d[] = $row->nama;
            $d[] = $row->email;
            $d[] = $row->telepon;
            $d[] = $row->alamat;
            $btn = '<a href="' . route('donatur.edit', $row->id) . '" class="btn  btn-primary" style="margin-right: 3px;">  <i class="far fa-edit"></i></a>';
            $btn .= '<a href="#" data-id="' . $row->id . '" class="btn btn-danger btn-del " >  <i class="fas fa-trash-alt"></i></a>';

            $d[] = sprintf('<span style="overflow: visible; position: relative; width: 110px;">%s</span>', $btn);
            $d["DT_RowId"] = ($i - 1) . '#' . $row['_id'];
            $table['data'][] = $d;
        }

        if (empty($table['data'])) {
            $table['recordsTotal'] = $count;
            $table['recordsFiltered'] = 0;
            $table['aaData'] = [];
        }

        return response()->json($table);
    }


    public function create()
    {
        return view('backend.pages.donatur.form');
    }

    public function store(Request $request)
    {
//        dd($request->all());
        $rules = [
            'nama' => 'required',
            'email' => 'required',
            'alamat' => 'required',
            'telepon' => 'required'
        ];
        $customMessages = [
            'nama.required' => 'Field Nama Donatur Wajib Diisi!',
            'email.required' => 'Field Email Donatur Wajib Diisi!',
            'alamat.required' => 'Field Jenis Donatur Wajib Diisi!',
            'telepon.required' => 'Field Jenis Donatur Wajib Diisi!'
        ];
        $this->validate($request, $rules, $customMessages);

        $input = $request->all();
        $status = Donatur::create($input);
        if ($status) {
            return redirect()->route('donasi.create')->with('success', 'Data berhasil ditambah');
        }

    }

    public function update(Request $request, $id)
    {
        $rules = [
            'nama' => 'required',
            'email' => 'required',
            'alamat' => 'required',
            'telepon' => 'required'
        ];
        $customMessages = [
            'nama.required' => 'Field Nama Donatur Wajib Diisi!',
            'email.required' => 'Field Email Donatur Wajib Diisi!',
            'alamat.required' => 'Field Alamat Donatur Wajib Diisi!',
            'telepon.required' => 'Field Jenis Donatur Wajib Diisi!'
        ];
        $this->validate($request, $rules, $customMessages);

        $donatur = Donatur::find($id);
        $input = $request->all();
        $status = $donatur->update($input);
        if ($status) {
            return redirect()->route('donatur.index')->with('success', 'Data berhasil diubah');
        }
    }

    public function edit($id)
    {
        $data['donatur'] = Donatur::find($id);
        return view('backend.pages.donatur.form',$data);
    }

    public function show($id)
    {
        $donatur = Donatur::where('id', $id)->first();
        return response()->json(['data' => $donatur]);
    }

    public function destroy($id)
    {
        $donatur = Donatur::find($id);
        $donatur->is_deleted = 1;
        $status = $donatur->save();

        if ($status) {
            return 1;
        } else {
            return 0;
        }
    }

    private function uploadImage(Request $request,$name){
        $image = $request->file('bukti_transfer');
        $ext = $image->getClientOriginalExtension();

        if($request->file('bukti_transfer')->isValid()){
            $upload_path = 'assets/uploads/donasi';
            $imagename = $upload_path.'/'.$name.'.'.$ext;
            $request->file('bukti_transfer')->move($upload_path,$imagename);
            return $imagename;
        }
        return false;
    }

    public function gantiStatus(Request $request){
        $donasi = Donasi::find($request->id);
        $donasi->transfer = $request->status;
        $status = $donasi->save();
        if ($status){
            return response(1);
        }
    }

    public function downloadBukti(Request $request){
        $donasi = Donasi::find($request->id);
        dd($donasi->bukti_transfer);
        $filepath = public_path($donasi->bukti_transfer);
        return response()->download($filepath);
    }

    public function getDonaturList(Request $request)
    {
        $input = $request->all();

        $data = Donatur::orderBy('id');
        if (@$input['search']) $data = $data->where('nama', 'like', '%' . $input['search'] . '%');

        $count = $data->count();

        if ($count > 10) $more = TRUE;
        else $more = FALSE;

        $data = $data->take(10)->skip(10 * ($input['page'] - 1))->get();
        $return = [];
        foreach ($data as $row) {
            $return[] = [
                'id' => $row->id,
                'text' => $row->nama.' - '.$row->alamat
            ];
        }

        return ['results' => $return, 'pagination' => ['more' => $more]];
    }

}

app/Http/Controllers/Front/DonaturController.php
<?php

namespace App\Http\Controllers\Front;

use App\Donatur;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DonaturController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.new-donatur');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('frontend.new-donatur');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getDonaturList(Request $request)
    {
        $input = $request->all();

        $data = Donatur::orderBy('id');
        if (@$input['search']) $data = $data->where('nama', 'like', '%' . $input['search'] . '%');

        $count = $data->count();

        if ($count > 10) $more = TRUE;
        else $more = FALSE;

        $data = $data->take(10)->skip(10 * ($input['page'] - 1))->get();
        $return = [];
        foreach ($data as $row) {
            $return[] = [
                'id' => $row->id,
                'text' => $row->nama.' - '.$row->alamat
            ];
        }
        return ['results' => $return, 'pagination' => ['more' => $more]];
    }

    public function getDonatur($id){
        $donatur = Donatur::where('id', $id)->first();
        return response()->json(['data' => $donatur]);
    }
}

resources/views/backend/pages/donatur/form.blade.php
@extends('backend.layouts.app')
@section('title','Dash')
@section('donasi','active')

@push('styles')
    <style>

    </style>
@endpush
@section('content')

    <div class="main-content">
        <sectiion>
            <div class="section-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item "><a href="{{route('donasi.index')}}">Data Donasi Masuk</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{@$donatur ? "Ubah" : "Tambah"}} Data Donasi Masuk</li>
                    </ol>
                </nav>
            </div>
        </sectiion>
        <section class="section">
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{@$donatur ? "Ubah" : "Tambah"}} Data Donasi</h4>
                            </div>

                            <div class="card-body">
                                <form action="{{@$donatur ? route('donatur.update', $donatur->id) : route('donatur.store')}}"  method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if(@$donatur)
                                        {{method_field('patch')}}
                                    @endif
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label for="sapaan">Sapaan Donatur</label>
                                                <select name="sapaan" id="sapaan" class="form-control">
                                                    <option value="Bapak" {{@$donatur->sapaan == 'Bapak' ? 'selected' : ''}}>Bapak</option>
                                                    <option value="Ibu" {{@$donatur->sapaan == 'Ibu' ? 'selected' : ''}}>Ibu</option>
                                                    <option value="Saudara" {{@$donatur->sapaan == 'Saudara' ? 'selected' : ''}}>Saudara</option>
                                                    <option value="Saudari" {{@$donatur->sapaan == 'Saudari' ? 'selected' : ''}}>Saudari</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label for="nama">Nama Donatur</label>
                                                <input type="text" class="form-control" name="nama" id="nama" value="{{old('nama',@$donatur->nama)}}">
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label for="email">Email Donatur</label>
                                                <input type="email" class="form-control" name="email" id="email" value="{{old('email',@$donatur->email)}}">
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label for="telepon">No. Telepon Donatur</label>
                                                <input type="number" class="form-control" name="telepon" id="telepon" min="0" value="{{old('telepon',@$donatur->telepon)}}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label for="email">Alamat Donatur</label>
                                                <textarea name="alamat" id="alamat" class="form-control" cols="30" rows="10">{{{old('alamat', @$donatur->alamat)}}}</textarea>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-button text-right">
                                        <a href="{{route('donatur.index')}}" class="btn btn-warning">Kembali</a>
                                        <button class="btn btn-primary" type="submit">Simpan</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $('[name=jenis_id]').select2({
                theme: 'bootstrap4',
                placeholder: '- Pilih Jenis Donasi -',
                ajax: {
                    url: '{{ route('jenis.getList') }}',
                    type: 'POST',
                    dataType: 'json',
                    data: function (params) {
                        var query = {
                            search: params.term,
                            page: params.page || 1,
                            _token: '{{ csrf_token() }}',
                        }
                        return query;
                    }
                }
            });
            $('[name=pengkhususan_id]').select2({
                placeholder: '- Pilih Pengkhususan -',
                ajax: {
                    url: '{{ route('pengkhususan.getList') }}',
                    type: 'POST',
                    dataType: 'json',
                    data: function (params) {
                        var query = {
                            search: params.term,
                            page: params.page || 1,
                            jenis_id: $('[name=jenis_id]').val(),
                            _token: '{{ csrf_token() }}',
                        }
                        return query;
                    }
                }
            });

            $("#jenis_id").on('change',function ()
            {
                $('#pengkhususan_id').prop('disabled', false);
            });
        });

    </script>

@endpush

resources/views/backend/pages/donatur/index.blade.php
@extends('backend.layouts.app')
@section('title','Dash')
@section('donatur','active')

@push('styles')
    <style>

    </style>
@endpush
@section('content')

    <div class="main-content">
        <sectiion>
            <div class="section-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Data Donatur Masuk</li>

                        <li class="breadcrumb-item"><a href="#"></a></li>
                        {{--                        <li class="breadcrumb-item active"><a href="#">Data Jenis</a></li>--}}
{{--                        <li class="breadcrumb-item active" aria-current="page">Data</li>--}}
                    </ol>
                </nav>
            </div>
        </sectiion>
        <section class="section">
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Data Donatur Masuk</h4>
                                <div class="card-header-action">
                                    <a href="{{ route('donatur.create') }}" class="btn btn-sm btn-primary float-right"><i class="fas fa-plus"></i> Tambah</a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-jenis">
                                        <thead>
                                        <tr>
                                            <th class="text-center">
                                                #
                                            </th>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>No. Telepon</th>
                                            <th>Alamat</th>
                                            <th>Aksi</th>
                                        </tr>
                                        </thead>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {



            $('#table-jenis').DataTable( {
                deferRender: true,
                serverSide: true,
                processing: true,
                stateSave: true,
                scrollX: false,
                ajax: {
                    url: '{!! route('donatur.get') !!}',
                    type: 'POST',
                    data: function (e) {
                        e._token = '{{ csrf_token() }}';
                        return e;
                    }
                }
            });

            $(document).on('click','.btn-del', function () {
                var id = $(this).data('id');
                swal({
                    title: 'Apakah Anda Yakin?',
                    text: 'Data yang telah dihapus tidak bisa dikembalikan!',
                    icon: 'warning',
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            type: "delete",
                            url: "{{ url('admin/donatur') }}/"+id,
                            data: {
                                '_token' : '{{ csrf_token() }}'
                            },
                            success: function (response) {
                                if(response == 1){
                                    swal('Data berhasil dihapus!', {
                                        icon: 'success',
                                    });
                                    setTimeout(() => {
                                        location.reload();
                                    }, 2000);
                                }else{
                                    swal('Data gagal dihapus!', {
                                        icon: 'error',
                                    });
                                }
                            }
                        });
                    }
                });
            });
        });

    </script>

@endpush